# Foot Configuration by Reend
# github: Reend21

app-id=foot
title=footTerm
locked-title=no

font=Hurmit Nerd Font:size=16
font-bold=yes
letter-spacing=1
box-drawings-uses-font-glyphs=yes

initial-color-theme=dark
initial-window-size-pixels=1024x768
initial-window-mode=windowed
resize-by-cells=yes
resize-keep-grid=yes
resize-delay-ms=25

bold-text-in-bright=yes
selection-target=primary

[bell]
system=yes
urgent=yes
notify=yes
visual=yes
command-focused=yes

[desktop-notifications]
command=notify-send --wait --app-name ${app-id} --icon ${app-id} --category ${category} --urgency ${urgency} --expire-time ${expire-time} --hint STRING:image-path:${icon} --hint BOOLEAN:suppress-sound:${muted} --hint STRING:sound-name:${sound-name} --replace-id ${replace-id} ${action-argument} --print-id -- ${title} ${body}
command-action-argument=--action ${action-name}=${action-label}

[scrollback]
lines=1000
multiplier=3.0

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
style=dashed
osc8-underline=url-mode

[cursor]
style=underline
blink=yes
blink-rate=259
beam-thickness=2
underline-thickness=3

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[touch]
long-press-delay=300

[key-bindings]
scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up
scrollback-down-page=Shift+Page_Down Shift+KP_Page_Down
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
