# Kitty configuration by Reend!
include Batman.conf

font_family HurmitNerdFont
font_size 14

map ctrl+q close_window

cursor_shape underline
cursor #f0d90e
cursor_text_color #f0d90e
cursor_underline_thickness 4.0
cursor_shape_unfocused block
cursor_blink_interval 0.8
cursor_stbackground_blur 3
backgrouncursor_shape underline
cursor #f0d90e
cursor_text_color #f0d90e
cursor_underline_thickness 4.0
cursor_shape_unfocused block
cursor_blink_interval 0.8
cursor_std_opacity 0.9
hide_window_decorations yes

cursor_shape underline
cursor #f0d90e
cursor_text_color #f0d90e
cursor_underline_thickness 4.0
cursor_shape_unfocused block
cursor_blink_interval 0.8
cursor_stop_blinking_after 0
cursor_trail 2
cursor_trail_color #ffff00

progress_bar bottom
repaint_delay 5
input_delay 2

enable_audio_bell yes

initial_window_width 1360
initial_window_height 768
remember_window_size no
remember_window_position no

active_border_color #f0d90e
inactive_border_color #ff6600

dynamic_background_opacity yes
background_tint 5.0
